/** ------- Constants -------- */
export const BLACK_MARKET = 'BLACK_MARKET';
export const CARAVANSARY = 'CARAVANSARY';
export const FABRIC_WAREHOUSE = 'FABRIC_WAREHOUSE';
export const FRUIT_WAREHOUSE = 'FRUIT_WAREHOUSE';
export const GEMSTONE_DEALER = 'GEMSTONE_DEALER';
export const GREAT_MOSQUE = 'GREAT_MOSQUE';
export const LARGE_MARKET = 'LARGE_MARKET';
export const SMALL_MARKET = 'SMALL_MARKET';
export const SMALL_MOSQUE = 'SMALL_MOSQUE';
export const SPICE_WAREHOUSE = 'SPICE_WAREHOUSE';
export const TEA_HOUSE = 'TEA_HOUSE';
export const WAINWRIGHT = 'WAINWRIGHT';
