/** CONSTANTS */
export const DROP_ASSISTANT = 'DROP_ASSISTANT';
export const MERCHANT_ENCOUNTER = 'MERCHANT_ENCOUNTER';
export const PICK_UP_ASSISTANT = 'PICK_UP_ASSISTANT';
export const SMUGGLER_ENCOUNTER = 'SMUGGLER_ENCOUNTER';
